# Generated by Django 5.1.6 on 2025-03-28 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportwear', '0003_cart_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sportwear.shoe'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
